sudo: required
services:
  - docker

before_install:
  - docker build -t mikercampbell/docker-ci-practice -f Dockerfile.dev .

script:
 - docker run mikercampbell/docker-ci-practice npm run test -- -- coverage