version: '3'
services:
  web:
    build:
      context: . # location of src dir
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app # Map current directory to app volume
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app # Map current directory to app volume
    command: ["npm", "run", "test"]